sonar.organization=arinabilan
sonar.projectKey=arinabilan_DevSecOps---Lab-VulnChecker

sonar.projectName=VulnChecker
sonar.sources=vulncheckerbackend/src/main,frontend/src
sonar.tests=vulncheckerbackend/src/test,frontend/src/__tests__
sonar.test.inclusions=**/*Test*,**/*test*,**/*Spec*,**/*spec*
sonar.exclusions=**/node_modules/**,**/target/**,**/src/test/**
sonar.java.binaries=vulncheckerbackend/target/classes
sonar.java.libraries=vulncheckerbackend/target/dependency/**/*.jar
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=vulncheckerbackend/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/config/**,**/dto/**,**/entities/**,**/repositories/**,**/VulncheckerbackendApplication.java
sonar.cpd.exclusions=**/src/test/**,**/__tests__/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
