sonar.organization=arinabilan
sonar.projectKey=arinabilan_DevSecOps---Lab-VulnChecker

sonar.projectName=VulnChecker
sonar.sources=vulncheckerbackend, frontend
sonar.exclusions=**/node_modules/**,**/target/**
sonar.java.binaries=vulncheckerbackend/target/classes

sonar.coverage.jacoco.xmlReportPaths=vulncheckerbackend/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/config/**,**/dto/**,**/entities/**,**/repositories/**,**/VulncheckerbackendApplication.java

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
