sonar.organization=arinabilan
sonar.projectKey=arinabilan_DevSecOps---Lab-VulnChecker

sonar.projectName=VulnChecker
sonar.sources=vulncheckerbackend, frontend
sonar.exclusions=**/node_modules/**
sonar.java.binaries=.
