-- =============================================================================
-- Migration: V1__initial_schema.sql
-- Target: PostgreSQL 16
-- Compatibility: Spring Boot 3.x / Hibernate 6.x (ddl-auto=validate)
-- =============================================================================

-- 1. Tabla: agents
CREATE TABLE agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    wazuh_agent_id VARCHAR(255),
    name VARCHAR(255),
    version VARCHAR(255),
    os_type VARCHAR(255),
    os_full_name VARCHAR(255),
    os_plataform VARCHAR(255), -- Se respeta el typo del diagrama/entidad
    last_seen TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_agents PRIMARY KEY (id)
);

-- 2. Tabla: credentials
CREATE TABLE credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_by_user_id BIGINT NOT NULL,
    username_credentials VARCHAR(255) NOT NULL,
    password_credentials VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_credentials PRIMARY KEY (id)
);

-- 3. Tabla: infrastructure_credentials
CREATE TABLE infrastructure_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    ssh_user VARCHAR(255),
    ssh_password VARCHAR(255),
    wazuh_user VARCHAR(255),
    wazuh_password VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_infrastructure_credentials PRIMARY KEY (id)
);

-- 4. Tabla: report_signatures
CREATE TABLE report_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    report_name VARCHAR(255),
    sha256_hash VARCHAR(64) NOT NULL,
    digital_signature TEXT NOT NULL,
    signed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_report_signatures PRIMARY KEY (id),
    CONSTRAINT uq_report_signatures_sha256 UNIQUE (sha256_hash)
);

-- 5. Tabla: users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL,
    paternal_last_name VARCHAR(255) NOT NULL,
    maternal_last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- 6. Tabla: vulnerabilities
CREATE TABLE vulnerabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    agent_id BIGINT, -- Soft FK hacia agents
    cve VARCHAR(255) NOT NULL,
    description TEXT,
    severity VARCHAR(255),
    cvss3_score DOUBLE PRECISION, -- Mapeo idóneo para java.lang.Double
    status VARCHAR(255),
    under_evaluation BOOLEAN, -- Mapeo para java.lang.Boolean (admite NULL)
    cti_reference VARCHAR(255),
    package_name VARCHAR(255),
    package_type VARCHAR(255),
    package_version VARCHAR(255),
    detection_time TIMESTAMP WITHOUT TIME ZONE,
    last_detection TIMESTAMP WITHOUT TIME ZONE,
    last_sync TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vulnerabilities PRIMARY KEY (id),
    CONSTRAINT uq_vulnerabilities_cve_agent_package UNIQUE (cve, agent_id, package_name)
);

-- 7. Tabla: vulnerability_snapshots
CREATE TABLE vulnerability_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    agent_id BIGINT NOT NULL, -- Soft FK hacia agents
    critical_count INTEGER NOT NULL, -- Tipos primitivos int mapean a NOT NULL
    high_count INTEGER NOT NULL,
    medium_count INTEGER NOT NULL,
    low_count INTEGER NOT NULL,
    total_count INTEGER NOT NULL,
    snapshot_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vulnerability_snapshots PRIMARY KEY (id)
);

-- 8. Tabla: vulnerability_timeline

-- 8.1. Habilitar extensión de series temporales
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- 8.2. Crear tabla unificada para la línea de tiempo
CREATE TABLE vulnerability_timeline (
    time TIMESTAMPTZ NOT NULL,
    agent_id BIGINT NOT NULL,
    cve VARCHAR(255) NOT NULL,
    package_name VARCHAR(255) NOT NULL,
    package_type VARCHAR(255),
    package_version VARCHAR(255),
    status VARCHAR(255) NOT NULL,       -- 'ACTIVE', 'RESOLVED'
    cvss3_score NUMERIC(3, 1),
    severity VARCHAR(255) NOT NULL,     -- 'Critical', 'High', 'Medium', 'Low'

    CONSTRAINT pk_vulnerability_timeline PRIMARY KEY (time, agent_id, cve, package_name) -- Obligatorio incluir 'time' por ser Hypertable
);

-- 3. Transformar la tabla estándar en una Hypertable particionada por tiempo (cada 7 días)
SELECT create_hypertable('vulnerability_timeline', 'time', chunk_time_interval => INTERVAL '7 days');

-- 4. Índices estratégicos optimizados para series de tiempo
CREATE INDEX idx_timeline_filters ON vulnerability_timeline (agent_id, cve, severity, status, time DESC);